[package]
name = "nightcycle/type-union-lib"
description = "a lightweight package for handy type refinement based value handling"
version = "0.1.0"
license = "Apache"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["src", "default.project.json", "LICENSE"]

[dependencies]

[dev-dependencies]
